global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['userservice:8100', 'wikidataservice:8101', 'hintservice:8200', 'webapp:8000']