ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View

=== Sign up
The following diagram shows how the sign up process of a user is done.

1. The client writes the credentials needed to create and account.
2. Check the credentials are valid in format.
3. Check that the fields that need to be unique are unique.
4. Returns if they are unique.
5. Create the user and store it in the Database.
6. Notify to what page the user should be redirected.
7. The user is redirected to the menu. The user can access to its statistics (interaction with the User service) and play the game.
8. Notify that the credentials are invalid.
9. The errors are shown and the user isn’t registered.

[plantuml,"Sign up diagram",png]
----
autonumber
actor User
participant FrontEnd
participant UserService
database Database

User -> FrontEnd: write credentials
FrontEnd -> UserService: check credentials' format
UserService -> Database: check uniqueness
Database --> UserService: return uniqueness

alt valid credentials
    UserService -> Database: user created
    UserService --> FrontEnd: redirect user
    FrontEnd --> User: show menu
else not valid
    UserService --> FrontEnd: notify credentials are invalid
    FrontEnd --> User: show errors
end
----

=== Login
The following diagram shows how the login process of a user is done.

1. The client writes the credentials needed to login.
2. Check the credentials are valid in format.
3. Check the credentials are valid for the user.
4. Return if the credentials are valid.
5. The user is authenticated.
6. The user is redirected to the menu. The user can access to its statistics (interaction with the UserService) and play the game.
7. Notify that the credentials are invalid.
8. The errors are shown and the user isn’t registered.

[plantuml,"Login diagram",png]
----
autonumber
actor User
participant FrontEnd
participant UserService
database Database

User -> FrontEnd: write credentials
FrontEnd -> UserService: check credentials' format
UserService -> Database: check credentials are valid
Database --> UserService: return if valid

alt valid credentials
    UserService --> FrontEnd: login
    FrontEnd --> User: redirect
else not valid
    UserService --> FrontEnd: notify credentials are invalid
    FrontEnd --> User: show errors
end
----

=== Game
The following diagram shows how the playing of the game is done.

1. Choses the game option in the menu.
2. The game starts.
3. See the Question Generation section below.
4. The data related to the question is returned.
5. User asks for a hint.
6. The timer is stopped.
7. See the Hint Generation section below.
8. The information related to the hint is returned.
9. User choses an option from the four given.
10. The GameService checks if the option picked is the answer or not to the question.
11. The GameService returns if it's correct the option picked.
12. The user is informed if they make a good guess or not.
13. Store the results and information of the game in the database.
14. Returns the information of the game to the FrontEnd.
15. The information of the game is shown to the user.

[plantuml,"Game diagram",png]
----
autonumber
actor User
participant FrontEnd
participant GameService
participant QuestionService
participant HintService
database Database

User -> FrontEnd: choses the game option
FrontEnd -> GameService: the game starts
loop round starts with timer (global or per round)
    GameService -> QuestionService: [Question generation part]
    QuestionService --> GameService: return data
    alt user asks for a hint
        User -> FrontEnd: ask for a hint
        FrontEnd -> GameService: stop timer
        GameService -> HintService: [Hint generation part]
        HintService --> FrontEnd: return hint

    else user chooses an option
        User -> FrontEnd: chooses an option
        FrontEnd -> GameService: check if correct
        GameService --> FrontEnd: returns if correct
        FrontEnd --> User: inform if correct
    end
end
GameService -> Database: store results
GameService --> FrontEnd: return the results
FrontEnd --> User: show the results
----

=== Question generation
The following diagram shows how the generation of the questions is done. This option loads the questions during the game directly from Wikidata.

1. The GameService asks for a question.
2. The QuestionService requests data for creating the questions.
3. Wikidata returns the question, image and options for the question.
4. The QuestionService returns all the information.
5. The GameService stores all the information returned.
6. The GameService returns the data to the FrontEnd
7. The question, image and options for the question are shown

[plantuml,"Question generation 1 diagram",png]
----
autonumber
actor User
participant FrontEnd
participant GameService
participant QuestionService
entity WikiData

GameService -> QuestionService: ask for a question
QuestionService -> WikiData: requests data
WikiData --> QuestionService: returns the data
QuestionService --> GameService: returns the data
GameService -> GameService: stores the data
GameService --> FrontEnd: returns the data
FrontEnd --> User: show the data
----

=== Hint generation
The following diagram shows how the generation of the hints is done.

1. The GameService (after the user asks it) asks for a hint to the current question.
2. The HintService gives some context to the LLM.
3. The LLM returns the clue.
4. The HintService returns the clue.

[plantuml,"Hint generation diagram",png]
----
autonumber
participant GameService
participant HintService
entity LLM

GameService -> HintService: ask for clue
HintService -> LLM: give context and ask for clue
LLM --> HintService: returns the clue
HintService --> GameService: returns the clue
----
