ifndef::imagesdir[:imagesdir: ../images]

[[section-design-decisions]]
== Architecture Decisions
=== Client/Server architecture
We are going to have an architecture with a main application with a client and server, and several servers for the external services (users, WikiData, LLM, etc.) that will act as data APIs for the main application server. These service servers will respond to requests by returning data that the main application will process and pass to the view.
This will provide us more independence between the modules so they can be modified at will without affecting the whole application.
=== MVC architectural pattern
We are going to follow and MVC architectural pattern as it allows for a more divided and structured application with low coupling.

=== MVC architectural pattern
We are going to follow and MVC architectural pattern as it allows for a more divided and structured application with low coupling.
This pattern works well with springboot, has low coupling, and allows to work independently with front and backend.

=== Microservices architecture
We are going to use a microservices architecture as it allows us to divide the whole application’s project into independent services that we can treat as separate projects that can be reusable.
With microservices, we would be able to divide the application in small teams that can work independently.

=== Backend
We are going to use a springboot. It is reusable, it contains many already implemented funtionalities and we are extremely familiar with the language (Java).

=== Frontend
We are going to use a springboot with thymeleaf. Springboot is reusable , it contains many already implemented funtionalities and we are extremely familiar with the language (Java).
In addition, thymeleaf allows access to model attributes, processes dynamically the templates and separates the user interface from the content.

=== Databases
We are going to use a non-relational database, MongoDB for the whole system.
It is easier to use just a single database system for the whole application. In addition MongoDB is based on JSON so it has a simple sintax with powerful operations and since we don't need complex relationships works well.
It's also very flexible since a collection can store different document and attribute types without a structure.

=== Cloud service
We have decided to use Oracle as our main service. It is less expensive than the alternatives and has good enough availability.
We however have decided to have Azure as a backup in case of an issue

=== LLM
We have decided to use Gemini since it is very powerful with ways to control hallucinations, allows instructions on the llm's behaviour, free of charge usage.
