package com.uniovi.wichatwebapp.entities;

public enum AnswerCategory {
    FLAG, MONUMENT_NAME, MONUMENT_COUNTRY, BRAND, MOVIE_YEAR, ANIMAL_NAME, ANIMAL_SCIENTIFIC_NAME, ANIMAL_LIFESPAN, PERSON_FOOTBALL_TEAM, PERSON_F1_TEAM, PERSON_BASKETBALL_TEAM, SPORT_TEAM_LOGO
}
